# ===========================================================
# export_tflite.py — PyTorch → TFLite via ONNX + onnx2tf
# ===========================================================
"""
Exports the trained model to TFLite for Android (NNAPI/GPU delegate).

Pipeline: PyTorch → ONNX (opset 17) → onnx2tf → TFLite.

onnx2tf v2.4+ uses a flatbuffer_direct backend by default, producing
.tflite files directly without needing TensorFlow. If a SavedModel is
also produced, we try tf.lite.TFLiteConverter for dynamic INT8 quantization.
"""

import os
import glob
import tempfile

import numpy as np
import torch
import torch.nn as nn

from scripts.config import MAX_SEQ_LENGTH, EXPORT_DIR


class _FlatWrapper(nn.Module):
    """Wraps HF classifier to return a plain logits tensor (no dict)."""

    def __init__(self, hf_model):
        super().__init__()
        self.model = hf_model
        self.model.config.return_dict = False

    def forward(self, input_ids, attention_mask):
        out = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            return_dict=False,
        )
        return out[0]  # logits


def _find_tflite(directory):
    """Find the float32 tflite file generated by onnx2tf."""
    patterns = ['*_float32.tflite', '*.tflite']
    for pat in patterns:
        matches = sorted(glob.glob(os.path.join(directory, pat)))
        if matches:
            return matches[0]
    return None


def export_tflite(tokenizer=None, calibration_texts=None, export_dir=None):
    """
    Export model to TFLite via ONNX → onnx2tf.

    Args:
        tokenizer: Unused (kept for API compatibility).
        calibration_texts: Unused (kept for API compatibility).
        export_dir: Override export directory.

    Returns:
        tflite_path: Path to saved .tflite file.
        tflite_size_mb: Size in MB.
    """
    export_dir = export_dir or EXPORT_DIR
    best_dir = os.path.join(export_dir, 'best_pytorch')

    print("=" * 60)
    print("EXPORT: TFLite (Android)")
    print("=" * 60)

    from transformers import AutoModelForSequenceClassification

    print("  Loading saved model...")
    hf_model = AutoModelForSequenceClassification.from_pretrained(best_dir)
    wrapper = _FlatWrapper(hf_model).eval().cpu().float()

    dummy_ids = torch.randint(0, 100, (1, MAX_SEQ_LENGTH), dtype=torch.long)
    dummy_mask = torch.ones(1, MAX_SEQ_LENGTH, dtype=torch.long)

    with tempfile.TemporaryDirectory() as tmp_dir:
        onnx_path = os.path.join(tmp_dir, 'model.onnx')
        out_dir = os.path.join(tmp_dir, 'onnx2tf_out')

        # Step 1: PyTorch → ONNX
        print("  [1/3] PyTorch → ONNX (opset 17)...")
        with torch.no_grad():
            torch.onnx.export(
                wrapper,
                (dummy_ids, dummy_mask),
                onnx_path,
                input_names=['input_ids', 'attention_mask'],
                output_names=['logits'],
                dynamic_axes={
                    'input_ids': {0: 'batch'},
                    'attention_mask': {0: 'batch'},
                    'logits': {0: 'batch'},
                },
                opset_version=17,
            )

        # Step 2: ONNX → TFLite via onnx2tf
        print("  [2/3] ONNX → TFLite (onnx2tf)...")
        import onnx2tf
        onnx2tf.convert(
            input_onnx_file_path=onnx_path,
            output_folder_path=out_dir,
            non_verbose=True,
            copy_onnx_input_output_names_to_tflite=True,
        )

        # Step 3: Try INT8 quantization via TFLiteConverter (if SavedModel exists)
        tflite_model = None
        quant_label = 'FP32'
        saved_model_pb = os.path.join(out_dir, 'saved_model.pb')

        if os.path.exists(saved_model_pb):
            try:
                print("  [3/3] Applying dynamic INT8 quantization...")
                import tensorflow as tf
                converter = tf.lite.TFLiteConverter.from_saved_model(out_dir)
                converter.optimizations = [tf.lite.Optimize.DEFAULT]
                tflite_model = converter.convert()
                quant_label = 'dynamic INT8'
            except Exception as e:
                print(f"  INT8 failed ({type(e).__name__}: {e})")

        # Fall back to onnx2tf's auto-generated float32 tflite
        if tflite_model is None:
            print("  [3/3] Using onnx2tf float32 output...")
            gen_tflite = _find_tflite(out_dir)
            if gen_tflite is None:
                raise FileNotFoundError(
                    f"No .tflite file found in {out_dir}. "
                    f"Contents: {os.listdir(out_dir)}"
                )
            with open(gen_tflite, 'rb') as f:
                tflite_model = f.read()

    # Save
    tflite_path = os.path.join(export_dir, 'support_ai.tflite')
    with open(tflite_path, 'wb') as f:
        f.write(tflite_model)

    tflite_size = os.path.getsize(tflite_path) / 1e6
    print(f"  TFLite: {tflite_size:.1f}MB ({quant_label})")

    return tflite_path, tflite_size
